### ISSUE TITLE
Error: Unknown ActiveXObject msxml2.serverxmlhttp

### ISSUE THREAD

**Issue by ndex11** [CapacitorSet/box-js#16]
Hello, 
I have this issue with Msxml2.ServerXMLHTTP ActiveXObject. 
--no-kill option not working.

Output:
`Analyzing x.jse
New ActiveXObject: WScript.Shell
New ActiveXObject: Scripting.FileSystemObject
New ActiveXObject: ADODB.Stream
New ActiveXObject: Shell.Application
New ActiveXObject: Msxml2.ServerXMLHTTP
C:\Users\xxx\Desktop\x\box-js-master\_controller.js:32
                        throw new Error(message);
                        ^

Error: Unknown ActiveXObject msxml2.serverxmlhttp
    at Object.kill (C:\Users\xxx\Desktop\x\box-js-master\_controller
.js:32:10)
    at new ActiveXObject (C:\Users\xxx\Desktop\x\box-js-master\analy
ze.js:326:15)
    at sample.js:97:13
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at Object.<anonymous> (C:\Users\xxx\Desktop\x\box-js-master\anal
yze.js:282:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

 * If you see garbled text, try emulating Windows XP with --windows-xp.
 * If the error is about a weird "Unknown ActiveXObject", try --no-kill.
 * If the error is about a legitimate "Unknown ActiveXObject", report a bug at h
ttps://github.com/CapacitorSet/box-js/issues/ .`

**Comment by CapacitorSet** [comment]
Thank you for your report! I'll need a sample to implement the necessary
features: if you're comfortable with sharing it publicly you can paste your
sample here, otherwise you can email me at capacitorset@gmail.com.
Il 31/gen/2017 10:23, "ndex11" <notifications@github.com> ha scritto:

**Comment by CapacitorSet** [comment]
Thank you, I added support for both msxml2.serverxmlhttp and a couple other features that were used in the script but missing in box-js. I'll write you an email with a more detailed analysis of the specific sample.
