### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by IndexDotZach** [CapacitorSet/box-js#2]
Hey I went to try your box-js tool and got the following error:

/home/zach/Tools/box-js-master/run.js:8
let timeout = argv.timeout || 10;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by CapacitorSet** [comment]
What is your Node version (`node --version`)? Because box-js relies on the `[Proxy](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Proxy)` object, it only supports Node 6.0 and higher. I think you may be running an older version.

**Comment by IndexDotZach** [comment]
Ah, it's saying I have node v4.2.6

I just did the install steps for 6.x using the following:
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

However, there was one error:
Err:13 http://ppa.launchpad.net/pwntools/binutils/ubuntu xenial/main amd64 Packages
  404  Not Found

Do you know any way around this or to troubleshoot?

**Comment by CapacitorSet** [comment]
The line `Err:13 http://ppa.launchpad.net/pwntools/binutils/ubuntu xenial/main amd64 Packages` appears to be an error with your apt configuration.

Go to `/etc/apt` and run `egrep -ir "(pwntools/binutils)" .` See which file contains the line in question (eg. `./sources.list`), open it as superuser in your text editor of choice (eg. `nano ./sources.list`), and delete the line that says `http://ppa.launchpad.net/pwntools/binutils/ubuntu xenial/main amd64`.

**Comment by IndexDotZach** [comment]
Ok that seems to work, I currnelty have v6.5.0 installed. But now when i go to run box-js I get this:

module.js:457
    throw err;
    ^

Error: Cannot find module 'walk'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zach/Tools/box-js-master/run.js:3:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by CapacitorSet** [comment]
Oh, yeah, you must install some dependencies for it to work: simply run `npm install`.

I'll add that to the README.

**Comment by CapacitorSet** [comment]
That's a component I haven't added yet, having never seen it in the viruses I received on my servers.

Could you please send me `sample.js` for review? You can either link to a pastebin or, if you prefer, email it at a0bb98d0@mailinator.com (temporary address).

**Comment by IndexDotZach** [comment]
Actually, tried with a different sample and it looks like it's working properly!

zach@zach-HP:~/Tools/box-js-master$ node run.js sample2.js
Using a 10 seconds timeout, pass --timeout to specify another timeout in seconds
Analyzing sample2.js
Faking a GET request to http://www.telescada.ru/grh5444tg?pPWkpIt=mtnYfSWdtN
Use the flag --download to actually download the file (eg. for encoded payloads).
Saved sample2.js.results/c9ea8a28-6468-4911-9088-b5145de21780 (65 bytes)
sample2.js.results/c9ea8a28-6468-4911-9088-b5145de21780 has been detected as ASCII text, with no line terminators.
Executing sample2.js.results/98e45428-f924-48fe-a0af-9cfa6eb6b581 in the WScript shell


Very excellent work sir! Fantastic tool, will definitely help me out when analyzing these malicious JS scripts I receive all the time.

Thank you!

**Comment by CapacitorSet** [comment]
Thank you, glad I could help!

**Comment by IndexDotZach** [comment]
Sure, here's the pastebin of the sample I threw at it that gave us the error

http://pastebin.com/YVhH9kin

Cheers

**Comment by CapacitorSet** [comment]
It appears that the site is either down or geolocked, unfortunately.
