### ISSUE TITLE
cc decoder.c -o decoder warning

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#20]
Hi  all
If i try to execute cc decoder.c -o decoder I get this Warning:
decoder.c: In function ‘ScriptDecoder’:
decoder.c:391:53: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
       printf ("Msg: Found encoded block containing %d characters.\n", len);
                                                     ^
Can someone help me?
regards

**Comment by CapacitorSet** [comment]
Thanks for the report.

You can safely ignore the warning, since `printf` will work correctly (and even if it didn't, it would be just a cosmetic issue). Either way, I'll fix the compiler warnings for -Wall/Wextra/pedantic and push a fix in minutes.
