### ISSUE TITLE
Function is not a constructor

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#27]
Hi @CapacitorSet  when i'm tryin to download payload of this JS 
https://malwr.com/analysis/ZTRlNmM3ZjZmODNiNGEyN2I1MTI3MWM5MDQzZTJlODI/
I got this error :	
throw this._internal.Decontextify.value(e);
			^
TypeError: Function is not a constructor
Can you help me?
best regards

**Comment by CapacitorSet** [comment]
This is almost certainly related to a6a3662b6052fc33bb8426ea6dd2a9c9d208e3ec. If you're in a hurry, try rolling back to a previous commit (eg. `git checkout dfc9a81`).

**Comment by Nwinternights** [comment]
no hurries :-) tks for the quick response.
