### ISSUE TITLE
Error: WScript.version not implemented!

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#28]
Hi ,
I got a jse that i decoded with the decoder of boxjs then I run the JS  with --preprocess --no-kill  parameters and I get this error: (on the bottom the urls for download the sample)
Using a 10 seconds timeout, pass --timeout to specify another timeout in seconds
[info] Rewriting code...
[info]     Preprocessing with uglify-js v3.0.24 (remove --preprocess to skip)...
[info]     Replacing `function A.prototype.B()` (use --no-rewrite-prototype to skip)...
[info]     Rewriting typeof calls (use --no-typeof-rewrite to skip)...
[info]     Rewriting eval calls (use --no-eval-rewrite to skip)...
[info]     Rewriting try/catch statements (use --no-catch-rewrite to skip)...
[info] Rewritten successfully.
[info] Rewriting code...
[info]     Preprocessing with uglify-js v3.0.24 (remove --preprocess to skip)...
[info]     Replacing `function A.prototype.B()` (use --no-rewrite-prototype to skip)...
[info]     Rewriting typeof calls (use --no-typeof-rewrite to skip)...
[info]     Rewriting eval calls (use --no-eval-rewrite to skip)...
[info]     Rewriting try/catch statements (use --no-catch-rewrite to skip)...
[info] Rewritten successfully.
/home/boxjs/node_modules/vm2/lib/main.js:213
			throw this._internal.Decontextify.value(e);
			^

Error: WScript.version not implemented!
    at Object.kill (/home//boxjs/lib.js:24:9)
    at Object.get (/home//boxjs/analyze.js:344:10)
    at Object.get (/home//boxjs/node_modules/vm2/lib/contextify.js:330:37)
    at vm.js:947:67
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at VM.run (/home//boxjs/node_modules/vm2/lib/main.js:207:72)
    at Object.<anonymous> (/home//boxjs/analyze.js:356:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

JS URL (https://malwr.com/analysis/ZWQxZWI0NTk1N2IyNDgyYTgyOGQ0NzA5NDBmMjdmNjE/)
JSE URL(https://malwr.com/analysis/MTliMTA4ZGUzYWJkNDM3ZDhkN2Q0NGRlYTI1NTFmNjA/)

**Comment by CapacitorSet** [comment]
Thanks for the report, I fixed the specific issue and also fixed the issue about cimv2 in WMI that had came up in #21.

**Comment by Nwinternights** [comment]
Thanks for the support!!
Regards

**Comment by Nwinternights** [comment]
gotta another interersting JSE , after passing it to the decoder i ran boxjs with standard parameters and I get this error
Trace: WScript.now not implemented!
    at Object.kill (/.../boxjs/lib.js:25:10)
    at Object.get (/.../boxjs/analyze.js:374:10)
    at Object.get (/../boxjs/node_modules/vm2/lib/contextify.js:330:37)
    at vm.js:1289:16
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at VM.run (...../boxjs/node_modules/vm2/lib/main.js:207:72)
    at Object.<anonymous> (/..../boxjs/analyze.js:401:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
[fatt-pdf-720649912 (copy).js.txt](https://github.com/CapacitorSet/box-js/files/1305653/fatt-pdf-720649912.copy.js.txt)
[fatt-pdf-720649912 (copy).jse.txt](https://github.com/CapacitorSet/box-js/files/1305654/fatt-pdf-720649912.copy.jse.txt)

**Comment by CapacitorSet** [comment]
Hmm, this is a peculiar sample, in that it seems to *know* that `WScript.Now` doesn't really exist and expects it to return `undefined`. The code looks like this:

```js
new ActiveXObject((WScript.Now + 'Shell.Application').substr(9, 17))
```

If `WScript.Now` returns `undefined`, the concatenation casts it to string, thus the code becomes `new ActiveXObject(('undefinedShell.Application').substr(9, 17))` which in turn becomes `new ActiveXObject('Shell.Application')`, a valid ActiveX object.

It's a tricky situation: to prevent such tricks, I would have to embed the list of all WScript properties and whatnot. I'll open a new issue about that.
