### ISSUE TITLE
TypeError: lib.warn is not a function

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#29]
Hi @CapacitorSet , 
This is what I get when running the js attached [NIC423523.js.TXT](https://github.com/CapacitorSet/box-js/files/1196940/NIC423523.js.TXT) :
 node run.js ../sample/js/NIC423523.js  --unsafe-preprocess --no-kill
Using a 10 seconds timeout, pass --timeout to specify another timeout in seconds
[info] Rewriting code...
[info]     Replacing `function A.prototype.B()` (use --no-rewrite-prototype to skip)...
[info]     Rewriting typeof calls (use --no-typeof-rewrite to skip)...
[info]     Rewriting eval calls (use --no-eval-rewrite to skip)...
[info]     Rewriting try/catch statements (use --no-catch-rewrite to skip)...
[info] Rewritten successfully.
[info] Rewriting code...
[info]     Replacing `function A.prototype.B()` (use --no-rewrite-prototype to skip)...
[info]     Rewriting typeof calls (use --no-typeof-rewrite to skip)...
[info]     Rewriting eval calls (use --no-eval-rewrite to skip)...
[info]     Rewriting try/catch statements (use --no-catch-rewrite to skip)...
[info] Rewritten successfully.
/home/...../boxjs/node_modules/vm2/lib/main.js:213
			throw this._internal.Decontextify.value(e);
			^

TypeError: lib.warn is not a function
    at Proxy.WScriptShell.regread (/home/...../boxjs/emulator/WScriptShell.js:67:7)
    at Object.apply (/home/....../boxjs/node_modules/vm2/lib/contextify.js:288:34)
    at eval (eval at <anonymous> (vm.js:30:19), <anonymous>:2:39)
    at vm.js:30:19
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at VM.run (/home/....../boxjs/node_modules/vm2/lib/main.js:207:72)
    at Object.<anonymous> (/home/--/boxjs/analyze.js:358:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

tks for your support

**Comment by CapacitorSet** [comment]
Whoops, it had slipped by. Thanks for the report!

**Comment by CapacitorSet** [comment]
Hmm, the sample still isn't analyzing correctly. Maybe I can also fix that.

**Comment by Nwinternights** [comment]
Tks as always for the quick fix.
now the Url is contacted but I get this error while tryin to download the payload:
"node run.js ../sample/js/NIC423523.js --preprocess --download --no-kill --timeout=1000"
[info] GET http://fly2.com.tw/nv44f33f
[info] Downloading...
[error] An error occurred while emulating a GET request to http://fly2.com.tw/nv44f33f.
[error] Error: Request timed out after 5006ms
[info] Saved NIC423523.js.10.results/3ba630a9-c8d0-4014-9007-452bbcbc40d6 (40 bytes)
[info] NIC423523.js.10.results/3ba630a9-c8d0-4014-9007-452bbcbc40d6 has been detected as ASCII text, with no line terminators.
[info] Executing: (Special folder Templates)\224510.exe   open 1

**Comment by CapacitorSet** [comment]
It means that the distribution site is down, no worries.

Anyway, it's still working for me. It downloads a PE32 file 293K large with hash `3a7cf1131fb5d7b200d76884a27d17e2`.
