### ISSUE TITLE
Add integration with Malwr

### ISSUE THREAD

**Issue by CapacitorSet** [CapacitorSet/box-js#33]

**Comment by Nwinternights** [comment]
It would awesome if it can be integrated via restful with cuckoosandbox .

**Comment by CapacitorSet** [comment]
@Nwinternights, great idea! I opened a new issue at #36, since it is a different topic with a different API.

**Comment by CapacitorSet** [comment]
Closing this, it was already fixed in ff6a389b6a3dda9a5b8bb50c756687bbe6681a11.
