### ISSUE TITLE
Add Reg_key on WScriptShell.js

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#35]
"HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\EXPLORER\SHELL FOLDERS\COMMONMUSIC": "C:\Users\Public\Music",
got some samples that search for that Key/folder.
regards

**Comment by CapacitorSet** [comment]
That was a temporary fix, but obviously not a stable solution - I'll add a list of registry key directly from Windows XP as soon as I get a decent network connection.
