### ISSUE TITLE
Embed list of WScript properties; return undefined for properties that are known not to exist

### ISSUE THREAD

**Issue by CapacitorSet** [CapacitorSet/box-js#38]
Some droppers rely on a technique similar to this:

```js
new ActiveXObject((WScript.Now + 'Shell.Application').substr(9, 17))
```

The code is only valid if `WScript.Now` returns `undefined`.

Because of this, box-js must have a list of all WScript properties, and replace the Proxy with a simple object that will return undefined for unknown properties.

**Comment by Nwinternights** [comment]
similar problem with that sample: https://www.reverse.it/sample/b2c00008d632c8260c160453e2cc488f67478da12fa46ec6926de971dba9c687?environmentId=100

"throw this._internal.Decontextify.value(e);
^
Error: WScriptShell.Exec not implemented!"

**Comment by CapacitorSet** [comment]
Thanks for the report, I fixed it in fce4254.

However, it wasn't of the same category, because WScriptShell.Exec [actually exists](https://msdn.microsoft.com/fr-fr/library/ateytk4a(v=vs.84).aspx). Anyway, I implemented that.

**Comment by Nwinternights** [comment]
hi @CapacitorSet the problem sussits
gotta this sample
https://www.reverse.it/sample/decd71ae3b5e683f0c3d057ac0576cbd624ca10734e1984f15cb77fcd23c4a37?environmentId=100
 TypeError: WScript.echo is not a function

**Comment by CapacitorSet** [comment]
Heh, for whatever reason, in JScript everything is case-sensitive but the WScript properties are case-insensitive. You can tell Microsoft worked on that.

Fixed in 1b8fa85, will upload the fixed Docker image in minutes.

**Comment by CapacitorSet** [comment]
Also, the script still isn't working, but now it gives another error. I'll be working on that.

**Comment by CapacitorSet** [comment]
Okay, it seems that you uncovered a non-trivial issue: unsurprisingly enough, there's *yet another* difference in the Microsoft implementation. In JavaScript, "Functions created with the Function constructor do not create closures to their creation contexts; they always are created in the global scope. When running them, they will only be able to access their own local variables and global ones, not the ones from the scope in which the Function constructor was called" ([MDN](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Function)). However, JScript completely ignores this. This means that in Node.js, this example has `x = 1`, and in JScript it has `x = 2`:

```js
var x = 1;
Function("x = 2")();
```
I'll open a new issue for that.
