### ISSUE TITLE
box-js

### ISSUE THREAD

**Issue by BW0LYNC** [CapacitorSet/box-js#41]
box-js

**Comment by CapacitorSet** [comment]
You too.

Jokes aside, do you need help with something?

**Comment by CapacitorSet** [comment]
I see you recently [pushed a commit](https://github.com/BW0LYNC/box-js/commit/fa720548044a8a824bbb37610719ef7f01d92717) to your fork of box-js. I'm guessing you were trying to open a PR to merge your code back into my codebase? In that case, I'm sorry but I'm already working on a Cuckoo plugin in a private repository. However, you're welcome to contribute bugfixes and new features when the plugin will be included in this repository.

**Comment by BW0LYNC** [comment]
GET results: %r" % e.message
 +            )
 +
 +    def _post_text(self, url, **kwargs):
 +        """Wrapper around doing a post and parsing its text output."""
 +        try:
 +            r = requests.post(url, timeout=self.timeout, **kwargs)
 +            return r.text() if r.status_code == 200 else {}
 +        except (requests.ConnectionError, ValueError) as e:
 +            raise CuckooOperationalError(
 +                "Unable to POST to the API server: %r" % e.message
 +            )
 +
 +    def _post_json(self, url, **kwargs):
 +        """Wrapper around doing a post and parsing its JSON output."""
 +        try:
 +            r = requests.post(url, timeout=self.

**Comment by CapacitorSet** [comment]
Please familiarize yourself with [issues](https://help.github.com/articles/about-issues/) and [pull requests](https://help.github.com/articles/about-pull-requests/). Closing this as invalid.
