### ISSUE TITLE
Review missing pdfdoc.alert

### ISSUE THREAD

**Issue by CapacitorSet** [CapacitorSet/box-js#50]
(see https://zaufanatrzeciastrona.pl/post/obszerna-analiza-zlosliwego-oprogramowania-na-polskim-przykladzie/)

**Comment by psrok1** [comment]
Script merges data from `Win32_Process` and `Win32_OperatingSystem` and checks for length + occurence of blacklisted elements characteristic for sandbox envs.  

'pdfdoc' is just a trap (undefined object).

https://gist.github.com/psrok1/eb591acb45975c6fa63118faa10c196b

**Comment by CapacitorSet** [comment]
Fixed! Among others, I accidentally [left VBox processes in processes.json](https://github.com/CapacitorSet/box-js/commit/96af59acd6e2512005387da05e02ea78598f61be), derp.
