### ISSUE TITLE
[error] Couldn't preprocess with uglify-es ..

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#51]
Hi, got this sample to analyze "https://www.reverse.it/sample/31641b7e48cf51ec19fc9c006f9ee1ecc8988b5c728f9a1386d2927c32718189?environmentId=100"   MD5:6f6067cacbc94d2019a7e2643645c60e 
but I get this error: 
Using a 10 seconds timeout, pass --timeout to specify another timeout in seconds
[error] Couldn't preprocess with uglify-es: {"message":"`cascade` is not a supported option","defs":{"arrows":true,"booleans":true,"collapse_vars":true,"comparisons":true,"computed_props":true,"conditionals":true,"dead_code":true,"drop_console":false,"drop_debugger":true,"ecma":5,"evaluate":true,"expression":false,"global_defs":{},"hoist_funs":false,"hoist_props":true,"hoist_vars":false,"ie8":false,"if_return":true,"inline":true,"join_vars":true,"keep_classnames":false,"keep_fargs":true,"keep_fnames":false,"keep_infinity":false,"loops":true,"negate_iife":true,"passes":1,"properties":true,"pure_getters":"strict","pure_funcs":null,"reduce_funcs":true,"reduce_vars":true,"sequences":true,"side_effects":true,"switches":true,"top_retain":null,"toplevel":false,"typeofs":true,"unsafe":false,"unsafe_arrows":false,"unsafe_comps":false,"unsafe_Function":false,"unsafe_math":false,"unsafe_methods":false,"unsafe_proto":false,"unsafe_regexp":false,"unsafe_undefined":false,"unused":true,"warnings":false}}

Any Ideas @CapacitorSet  ? 
regards

**Comment by CapacitorSet** [comment]
Thanks for the report, it's an incompatiblity caused by a small change in uglify-es (mishoo/UglifyJS2#2586). I fixed it in c1f541143cc8487039313d263ff992cce9a90923, and pushed a patch (v1.9.9).

**Comment by Nwinternights** [comment]
@CapacitorSet gotta the same error with parameters --preprocess. 
If not gotta the common error :/usr/lib/node_modules/box-js/node_modules/vm2/lib/main.js:218
			throw this._internal.Decontextify.value(e);
			^
SyntaxError: Invalid or unexpected token
"analyze.js is updated"

**Comment by CapacitorSet** [comment]
Lo stesso errore, sempre "`cascade` is not a supported option"? Strano, in teoria con quel commit ho tolto l'opzione per cui dovrebbe andare. Sei sicuro di avere l'ultima versione? Considera che se usi il webserver per Cuckoo, devi riavviarlo per fargli ricostruire il container e quindi scaricare l'ultima versione.

Non ho potuto scaricare il sample da reverse.it perchè vogliono un account ricercatore, però ho provato su un sample banale (`a = 1`) e con --preprocess funziona.

**Comment by Nwinternights** [comment]
E' sempre qualcosa riguardante il binario vecchio, ti faccio sapere ma sicuramente è un problema della mia macchina. non lo sto usando ora con cuckoo.
grazie ancora

**Comment by Nwinternights** [comment]
ok , risolto il problema del binario vecchio, ora non da più quell'errore ma comunque l'analisi non va a buon fine.  ti invio il sample 
[jransom.txt](https://github.com/CapacitorSet/box-js/files/1720816/jransom.txt)

**Comment by CapacitorSet** [comment]
Pare essere molto offuscato, ci sono almeno due livelli di offuscamento che dipendono uno dall'altro. Vedo se riesco a tirare fuori qualcosa.
