### ISSUE TITLE
Help with makeProcList.js

### ISSUE THREAD

**Issue by doomedraven** [CapacitorSet/box-js#54]
Hello, after execute `gwmi -Query "SELECT * FROM Win32_Process" > a.txt` in win7
and move it to vm with box-js and node 8.10.0 it returns error, i tried to fix it by myself but im new to node

* error, it looks like for some reason it adds that to the end of the dictionary
```
nodejs makeProcList.js
undefined:2
"": undefined},
    ^
```

from what i googled `JSON.stringify` should clean it, but the real fail happens here `JSON.parse(jsonString)`

would appreciate any help
best regards

**Comment by CapacitorSet** [comment]
Whoops, I had replied by e-mail but it seems that the message did not go through.

Can you upload an example file that exhibits the bug?

**Comment by doomedraven** [comment]
paste will be burned after read, https://0bin.net/paste/CKhZWGiccqJvPDEW#iCrhPMAm3AS7K1tTENlBmLblknyta2CT1O8J2wN3Tly

that is direct dump of file without touching it

**Comment by CapacitorSet** [comment]
Thanks, fixed in 0408636 (v1.9.13).

**Comment by doomedraven** [comment]
thanks for great tool :)

**Comment by doomedraven** [comment]
one small thing, are you sure you need log.console there? https://github.com/CapacitorSet/box-js/commit/04086366574f48630cacfb2f4255c56c59ff5b1b#diff-f29339ef5c6333e55bf7611a8df0464eR17

**Comment by CapacitorSet** [comment]
Yup, I forgot it in. I noticed it just after pushing, and force-pushed a fix; the commit is now e53be63.
