### ISSUE TITLE
FileSystemObject.GetParentFolderName not implemented

### ISSUE THREAD

**Issue by urunotao** [CapacitorSet/box-js#65]
I get FileSystemObject.GetParentFolderName not implemented when running a particularly brainy js code that has some pretty good anti-sandbox evasion builtin... Any suggestions?

**Comment by CapacitorSet** [comment]
You can implement the function in [`emulator/FileSystemObject.js`](https://github.com/CapacitorSet/box-js/blob/master/emulator/FileSystemObject.js) with the [Node.js `path.win32` APIs](https://nodejs.org/api/path.html).

If you do end up doing that, please send a PR.
