### ISSUE TITLE
Box-JS was integrated in Intel Owl - easy to use GUI

### ISSUE THREAD

**Issue by Eshaan7** [CapacitorSet/box-js#69]
Hi. We at [Intel Owl](https://github.com/intelowlproject/IntelOwl) recently added support for Box-JS. 

Intel Owl is a completely free and open source threat intelligence gathering tool that integrates a lot of external services and analyzers. If someone wants to request scans through Box-JS (and many other analyzers) they can do so easily with our web GUI - get the result from all the files such as `resources.json`, `IOC.json`, `urls.json`, etc all together in a prettified format which can be filtered/sorted/search through and is saved into the DB.

This is NOT meant to be an "advertisement" for Intel Owl nor a replacement to Box-JS - We support Box-JS. I decided to drop some info about this here because these could be some really nice features for Box-JS users to speed up their threat intelligence operations. 

I hope you don't mind and thank you for creating this amazing tool!

EDIT: Added link to Box-JS's LICENSE to the [project's README](https://github.com/intelowlproject/IntelOwl/tree/develop#legal-notice).

**Comment by CapacitorSet** [comment]
Thank you for the heads up! I added a mention in the readme.
