### ISSUE TITLE
SyntaxError regarding 'import' when running box.js

### ISSUE THREAD

**Issue by connorkas** [CapacitorSet/box-js#77]
I'm attempting to run box.js on a sample piece of malware, and it seems to be having an issue with the sample file importing different libraries.
This is the error I receive when attempting to run box.js:

Command:
» **box-js sample-malware.js --no-rewrite** 

Output:
 ```      
Using a 10 seconds timeout, pass --timeout to specify another timeout in seconds
/usr/local/lib/node_modules/box-js/node_modules/vm2/lib/transformer.js:82
		throw e;
		^

vm.js:110
import u from "path";
^^^^^^

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
    at makeNiceSyntaxError (/usr/local/lib/node_modules/box-js/node_modules/vm2/lib/transformer.js:41:16)
    at transformer (/usr/local/lib/node_modules/box-js/node_modules/vm2/lib/transformer.js:80:8)
    at VM.run (/usr/local/lib/node_modules/box-js/node_modules/vm2/lib/vm.js:491:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/box-js/analyze.js:529:8)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.7.2

 * If the error is about a weird "Unknown ActiveXObject", try --no-kill.
 * Otherwise, report a bug at https://github.com/CapacitorSet/box-js/issues/ .
 ```
 If I run box.js without the `--no-rewrite` flag, I get the following output:
 ```
[error] Couldn't parse with Acorn:
[error] SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
[error] 
[error] Decode JSE. 'cc decoder.c -o decoder'. './decoder ${filename} ${filename}.js'
 ```
 
 The beginning of the malware file contains the following imports:
 ```js
import u from "path";
import a from "fs";
import o from "https";
 ```
 
 Appreciate the support. Thank you!

**Comment by CapacitorSet** [comment]
>The beginning of the malware file contains the following imports:
>
>```js
>import u from "path";
>import a from "fs";
>import o from "https";
>```

The file is a Node.js script, while this project targets Microsoft JScript.

While it is out of scope for this project, here are some pointers for adding support. What I would do is replace the imports with something like this:

```js
u = PathStub;
a = FSStub;
o = HTTPSStub;
```

and then augment the [sandbox](https://github.com/CapacitorSet/box-js/blob/master/analyze.js#L423) with something like:

```js
PathStub: new Proxy({
        join: function(...) {...},
        ...
    }, {
        get: function(target, name) {
            if (name in target) return target[name];
            console.log(`Error: accessing ${name} on PathStub`);
        },
    })
```

where `join` is an implementation of `require("path").join`.

This is generally a tedious process, but I see you're trying to emulate `peacenotwar` so it should be simple enough, it's just:

 - proxying the functions from `require("path")`, for `PathStub` (I would recommend against `PathStub: require("path")`);
 - rebranding [`XMLHTTP`](https://github.com/CapacitorSet/box-js/blob/master/emulator/XMLHTTP.js) to `HTTPSStub`, mostly changing a couple of names;
 - taking inspiration from [`FileSystemObject`](https://github.com/CapacitorSet/box-js/blob/master/emulator/FileSystemObject.js) for `FSStub`.
